---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:
          - name: Install aptitude
            apt:
                    name: aptitude
                    state: present
                    update_cache: true

          - name: Install required system packages
            apt:
                    pkg:
                            - apt-transport-https
                            - gnupg
                            - curl
                            - ca-certificates
                            - software-properties-common
                            - python3-pip
                            - virtualenv
                            - python3-setuptools
                            - lsb-release
                    state: latest
                    update_cache: true

          - name: Add Docker GPG apt key
            apt_key:
                     url: "{{  apt_gpg_key  }}"
                     state: present

          - name: Add Docker repository
            apt_repository:
                     repo: docker_apt_repository
                     state: present

          - name: Update apt and install Docker
            apt:
                     name: "docker-ce={{ docker_version }}"
                     state: present
                     update_cache: true

          - name: Install Docker additional components
            apt:
                    name: "docker-ce-cli={{ docker_ce_cli_version }}"
                    state: present
                    update_cache: true

          - name: Install Containerd
            apt:
                    name: "containerd.io={{ containerd_version }}"
                    state: present
                    update_cache: true

          - name: Install Docker-compose-plugin
            apt:
                    name: docker-compose-plugin
                    state: latest
                    update_cache: true

          - name: Install Docker module for Python
            pip:
                     name: docker


