---

- hosts: all
  become: yes
  gather_facts: yes
  vars:
          Docker_version: 5:20.10.17~3-0~debian-buster
          Docker_ce_cli_version: 5:20.10.17~3-0~debian-buster
          Containerd_version: 1.6.6-1

  tasks:
          - name: Install aptitude
            apt:
                    name: aptitude
                    state: present
                    update_cache: true

          - name: Install required system packages
            apt:
                    pkg:
                            - apt-transport-https
                            - gnupg
                            - curl
                            - ca-certificates
                            - software-properties-common
                            - python3-pip
                            - virtualenv
                            - python3-setuptools
                            - lsb-release
                    state: latest
                    update_cache: true

          - name: Add Docker GPG apt key
            apt_key:
                     url: https://download.docker.com/linux/ubuntu/gpg
                     state: present

          - name: Add Docker repository
            apt_repository:
                     repo: deb https://download.docker.com/linux/debian buster stable
                     state: present

          - name: Update apt and install Docker
            apt:
                     name: "docker-ce={{ Docker_version }}"
                     state: present
                     update_cache: true

          - name: Install Docker additional components
            apt:
                    name: "docker-ce-cli={{ Docker_ce_cli_version }}"
                    state: present
                    update_cache: true

          - name: Install Containerd
            apt:
                    name: "containerd.io={{ Containerd_version }}"
                    state: present
                    update_cache: true

          - name: Install Docker-compose-plugin
            apt:
                    name: docker-compose-plugin
                    state: latest
                    update_cache: true

          - name: Install Docker module for Python
            pip:
                     name: docker


